# Generated by Django 3.2.6 on 2023-05-24 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_userprofile_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.TimeField(auto_now_add=True)),
                ('friend_list', models.ManyToManyField(blank=True, related_name='_user_log_userlog_friend_list_+', to='user_log.UserLog')),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='_user_log_userlog_friend_requests_+', to='user_log.UserLog')),
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to='user_profile.userprofile')),
            ],
        ),
    ]
