# Generated by Django 3.2.6 on 2023-07-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='last_login',
        ),
    ]
