# Generated by Django 4.2.1 on 2023-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0002_auto_20230605_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to='user_log.userlog'),
        ),
    ]
