# Generated by Django 4.2.1 on 2023-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0002_remove_userlog_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to='user_log.userlog'),
        ),
    ]
