# Generated by Django 4.0.4 on 2023-10-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0002_remove_userlog_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='friend_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlog',
            name='public_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='tag_visible',
            field=models.BooleanField(default=False),
        ),
    ]
