# Generated by Django 3.2.6 on 2023-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0007_alter_userlog_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='friend_list',
            field=models.ManyToManyField(blank=True, related_name='_user_log_userlog_friend_list_+', to='user_log.UserLog'),
        ),
    ]
