# Generated by Django 3.2.6 on 2023-07-05 14:21

from django.db import migrations, models
import django.db.models.deletion
import posts.models
import supercell_mates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', supercell_mates.models.DateTimeFieldNTZ()),
                ('rep_img', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupFileMessage',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', supercell_mates.models.DateTimeFieldNTZ(auto_now_add=True)),
                ('file_field', models.FileField(upload_to='message/')),
                ('file_name', models.CharField(max_length=100)),
                ('is_image', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTextMessage',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', supercell_mates.models.DateTimeFieldNTZ(auto_now_add=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', supercell_mates.models.DateTimeFieldNTZ()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateFileMessage',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', supercell_mates.models.DateTimeFieldNTZ(auto_now_add=True)),
                ('file_field', models.FileField(upload_to='message/')),
                ('file_name', models.CharField(max_length=100)),
                ('is_image', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateTextMessage',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', supercell_mates.models.DateTimeFieldNTZ(auto_now_add=True)),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_messages', to='message.privatechat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
