# Generated by Django 3.2.6 on 2023-06-16 12:19

from django.conf import settings
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='private',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='rep_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='users',
            field=models.ManyToManyField(related_name='group_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('users', models.ManyToManyField(related_name='private_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
