# Generated by Django 3.2.6 on 2023-07-12 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetextmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_text_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatefilemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_messages', to='message.privatechat'),
        ),
        migrations.AddField(
            model_name='privatefilemessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_file_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='users',
            field=models.ManyToManyField(related_name='private_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouptextmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_messages', to='message.groupchat'),
        ),
        migrations.AddField(
            model_name='grouptextmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_text_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupfilemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_messages', to='message.groupchat'),
        ),
        migrations.AddField(
            model_name='groupfilemessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_file_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='admins',
            field=models.ManyToManyField(related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='users',
            field=models.ManyToManyField(related_name='group_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
