# Generated by Django 3.2.6 on 2023-06-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20230617_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfilemessage',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='privatefilemessage',
            name='is_image',
        ),
    ]
