# Generated by Django 3.2.6 on 2023-06-17 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_textmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTextMessage',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_messages', to='message.groupchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_text_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateTextMessage',
            fields=[
                ('id', models.CharField(default=posts.models.random_str, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_messages', to='message.privatechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_text_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TextMessage',
        ),
    ]
