# Generated by Django 3.2.6 on 2023-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20230617_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
