# Generated by Django 3.2.6 on 2023-07-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_groupchat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='admins',
            field=models.ManyToManyField(related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
