# Generated by Django 3.2.6 on 2023-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_tagrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, upload_to='tag/'),
        ),
        migrations.AddField(
            model_name='tagrequest',
            name='icon',
            field=models.ImageField(blank=True, upload_to='tag/'),
        ),
    ]
