# Generated by Django 3.2.6 on 2023-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20230603_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagrequest',
            old_name='icon',
            new_name='image',
        ),
    ]
