# Generated by Django 3.2.6 on 2023-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_rename_icon_tagrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagrequest',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
