# Generated by Django 3.2.6 on 2023-06-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_tagrequest_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
