# Generated by Django 3.2.6 on 2023-07-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_adminapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tagrequest',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
