# Generated by Django 3.2.6 on 2023-07-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='user_auth.userauth')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile/img/')),
                ('tag_count_limit', models.IntegerField(default=4)),
                ('tagList', models.ManyToManyField(related_name='user_profiles', to='user_auth.Tag')),
            ],
        ),
    ]
