# Generated by Django 3.2.6 on 2023-05-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_tagrequest'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tagList',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tagList',
            field=models.ManyToManyField(related_name='user_profiles', to='user_auth.Tag'),
        ),
    ]
