# Generated by Django 3.2.6 on 2023-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tag_count_limit',
            field=models.IntegerField(default=4),
        ),
    ]
