# Generated by Django 4.0.4 on 2023-12-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_freq_post_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='readme',
            field=models.TextField(default=''),
        ),
    ]
