# Generated by Django 3.2.6 on 2023-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_postimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
