# Generated by Django 3.2.6 on 2023-06-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_count',
            field=models.IntegerField(default=0),
        ),
    ]
